// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	context "context"

	request "github.com/koenno/currency-price-monitor/request"
	mock "github.com/stretchr/testify/mock"
)

// Processor is an autogenerated mock type for the Processor type
type Processor[T interface{}] struct {
	mock.Mock
}

type Processor_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *Processor[T]) EXPECT() *Processor_Expecter[T] {
	return &Processor_Expecter[T]{mock: &_m.Mock}
}

// Process provides a mock function with given fields: _a0, _a1
func (_m *Processor[T]) Process(_a0 context.Context, _a1 request.Descriptor[T]) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, request.Descriptor[T]) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Processor_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type Processor_Process_Call[T interface{}] struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 request.Descriptor[T]
func (_e *Processor_Expecter[T]) Process(_a0 interface{}, _a1 interface{}) *Processor_Process_Call[T] {
	return &Processor_Process_Call[T]{Call: _e.mock.On("Process", _a0, _a1)}
}

func (_c *Processor_Process_Call[T]) Run(run func(_a0 context.Context, _a1 request.Descriptor[T])) *Processor_Process_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request.Descriptor[T]))
	})
	return _c
}

func (_c *Processor_Process_Call[T]) Return(_a0 error) *Processor_Process_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Processor_Process_Call[T]) RunAndReturn(run func(context.Context, request.Descriptor[T]) error) *Processor_Process_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewProcessor creates a new instance of Processor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProcessor[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *Processor[T] {
	mock := &Processor[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
