// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	request "github.com/koenno/currency-price-monitor/request"
)

// Requester is an autogenerated mock type for the Requester type
type Requester struct {
	mock.Mock
}

type Requester_Expecter struct {
	mock *mock.Mock
}

func (_m *Requester) EXPECT() *Requester_Expecter {
	return &Requester_Expecter{mock: &_m.Mock}
}

// Process provides a mock function with given fields: _a0
func (_m *Requester) Process(_a0 *http.Request) (request.Descriptor, error) {
	ret := _m.Called(_a0)

	var r0 request.Descriptor
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Request) (request.Descriptor, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*http.Request) request.Descriptor); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(request.Descriptor)
	}

	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Requester_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type Requester_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - _a0 *http.Request
func (_e *Requester_Expecter) Process(_a0 interface{}) *Requester_Process_Call {
	return &Requester_Process_Call{Call: _e.mock.On("Process", _a0)}
}

func (_c *Requester_Process_Call) Run(run func(_a0 *http.Request)) *Requester_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request))
	})
	return _c
}

func (_c *Requester_Process_Call) Return(_a0 request.Descriptor, _a1 error) *Requester_Process_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Requester_Process_Call) RunAndReturn(run func(*http.Request) (request.Descriptor, error)) *Requester_Process_Call {
	_c.Call.Return(run)
	return _c
}

// NewRequester creates a new instance of Requester. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRequester(t interface {
	mock.TestingT
	Cleanup(func())
}) *Requester {
	mock := &Requester{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
